### PR TITLE
handled create feedback route.

### LINKED ISSUE #34: [Backend-routes] POST api/v1/feedback
## Description
- This route allows users to add feedback. 

### Request body
```
{
content: string
}
```
#### Response 201
```
{
message :  تم إضافة التعليق بنجاح
 } 
```

Fail: 401
```
{
    "statusCode": 401,
    "message": "Unauthorized"
}
```

Fail: 500
```
{
  message: "حدث خطأ داخلي بالنظام "
  statusCode: 500
}
```

### PR DESCRIPTION
**Pull request by Bas-Shiekh**
relates #34

### CODE REVIEW

File: server/src/feedback/feedback.controller.ts [hunk 1]
```diff
@@ -6,17 +6,28 @@ import {
...
+import { JwtAuthGuard } from '../auth/strategy';
+import { Role } from '../auth/enums/role.enum';
+import { GetUser } from '../auth/decrator';
 
 @Controller('feedback')
 export class FeedbackController {
   constructor(private readonly feedbackService: FeedbackService) {}
 
+  @Roles(Role.Admin)
+  @UseGuards(JwtAuthGuard, RolesGuard)
```
Comment (MohammedOmar123) [inline server/src/feedback/feedback.controller.ts]: This route must be available for all authorized users, so just check the token using JwtAuthGuard and delete RolesGuard and  @Roles(Role.Admin).

**Review by MohammedOmar123 — APPROVED** [review]
